Add Note about the borked 2.x version in the README
symphonycms/jit_image_manipulation pull request #163
Opened 2018-10-09 09:56 UTC by animaux

;)

2018-10-19 20:32 UTC, nitriques approved these changes

2018-10-19 20:32 UTC, nitriques requested changes

2018-10-19 20:32 UTC, nitriques commented on README.markdown
> +
Can you add this link https://github.com/symphonycms/jit_image_manipulation/tree/1.x please ?

2018-10-24 21:55 UTC, nitriques approved these changes

2018-10-24 21:55 UTC, merged

2018-10-25 01:10 UTC, brendo commented
Hmm, how can I help here? [master...integration](https://github.com/symphonycms/jit_image_manipulation/compare/integration) has 104 commits difference, surely `integration` can be released?

2019-07-16 08:39 UTC, andrewminton commented
HAs this been tested with php7.3 at all?

2019-07-16 08:52 UTC, animaux commented
@andrewminton Version 2 is still a deadend. JIT 1.46 runs fine on PHP 7.3.

2019-07-16 09:03 UTC, andrewminton commented
Thanks for info!

2019-07-16 09:06 UTC, animaux commented
My pleasure ;)